all: CS490FinalPaper.ms
	pdfroff -ms CS490FinalPaper.ms  > CS490FinalPaper.pdf
	#GROFF_TMAC_PATH=./tmac troff -ms CS490FinalPaper.ms > CS490FinalPaper.ps

clean: CS490FinalPaper.pdf
	rm CS490FinalPaper.pdf
